# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/server"
bin = "tmp/app"
full_bin = "./tmp/app"
delay = 1000  # ms delay
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "bin", "tmp", "node_modules", "scripts"]

[log]
time = true

[serve]
cmd = "./tmp/app"
