// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/grpc/service.proto

package iot_metric_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temperature   float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Battery       float64                `protobuf:"fixed64,3,opt,name=battery,proto3" json:"battery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_pkg_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *MetricRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *MetricRequest) GetBattery() float64 {
	if x != nil {
		return x.Battery
	}
	return 0
}

type ConfigRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TemperatureThreshold float64                `protobuf:"fixed64,1,opt,name=temperature_threshold,json=temperatureThreshold,proto3" json:"temperature_threshold,omitempty"`
	BatteryThreshold     float64                `protobuf:"fixed64,2,opt,name=battery_threshold,json=batteryThreshold,proto3" json:"battery_threshold,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_pkg_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigRequest) GetTemperatureThreshold() float64 {
	if x != nil {
		return x.TemperatureThreshold
	}
	return 0
}

func (x *ConfigRequest) GetBatteryThreshold() float64 {
	if x != nil {
		return x.BatteryThreshold
	}
	return 0
}

type PostMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metric        *MetricRequest         `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMetricsRequest) Reset() {
	*x = PostMetricsRequest{}
	mi := &file_pkg_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMetricsRequest) ProtoMessage() {}

func (x *PostMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMetricsRequest.ProtoReflect.Descriptor instead.
func (*PostMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *PostMetricsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PostMetricsRequest) GetMetric() *MetricRequest {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Config        *ConfigRequest         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_pkg_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfig() *ConfigRequest {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_pkg_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_pkg_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *Alert) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Alert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Alert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AlertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusResponse        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Alerts        []*Alert               `protobuf:"bytes,2,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertList) Reset() {
	*x = AlertList{}
	mi := &file_pkg_grpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertList) ProtoMessage() {}

func (x *AlertList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertList.ProtoReflect.Descriptor instead.
func (*AlertList) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *AlertList) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AlertList) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type PostMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusResponse        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMetricsResponse) Reset() {
	*x = PostMetricsResponse{}
	mi := &file_pkg_grpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMetricsResponse) ProtoMessage() {}

func (x *PostMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMetricsResponse.ProtoReflect.Descriptor instead.
func (*PostMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *PostMetricsResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusResponse        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_pkg_grpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConfigResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusResponse        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Alerts        []*Alert               `protobuf:"bytes,2,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsResponse) Reset() {
	*x = GetAlertsResponse{}
	mi := &file_pkg_grpc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsResponse) ProtoMessage() {}

func (x *GetAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAlertsResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_grpc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PostLimiterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceRate    float64                `protobuf:"fixed64,2,opt,name=device_rate,json=deviceRate,proto3" json:"device_rate,omitempty"`
	DeviceBurst   int32                  `protobuf:"varint,3,opt,name=device_burst,json=deviceBurst,proto3" json:"device_burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLimiterRequest) Reset() {
	*x = PostLimiterRequest{}
	mi := &file_pkg_grpc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLimiterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLimiterRequest) ProtoMessage() {}

func (x *PostLimiterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLimiterRequest.ProtoReflect.Descriptor instead.
func (*PostLimiterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *PostLimiterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PostLimiterRequest) GetDeviceRate() float64 {
	if x != nil {
		return x.DeviceRate
	}
	return 0
}

func (x *PostLimiterRequest) GetDeviceBurst() int32 {
	if x != nil {
		return x.DeviceBurst
	}
	return 0
}

type PostLimiterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusResponse        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLimiterResponse) Reset() {
	*x = PostLimiterResponse{}
	mi := &file_pkg_grpc_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLimiterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLimiterResponse) ProtoMessage() {}

func (x *PostLimiterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLimiterResponse.ProtoReflect.Descriptor instead.
func (*PostLimiterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_service_proto_rawDescGZIP(), []int{12}
}

func (x *PostLimiterResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pkg_grpc_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_service_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/grpc/service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\rMetricRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x18\n" +
	"\abattery\x18\x03 \x01(\x01R\abattery\"q\n" +
	"\rConfigRequest\x123\n" +
	"\x15temperature_threshold\x18\x01 \x01(\x01R\x14temperatureThreshold\x12+\n" +
	"\x11battery_threshold\x18\x02 \x01(\x01R\x10batteryThreshold\"Y\n" +
	"\x12PostMetricsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12&\n" +
	"\x06metric\x18\x02 \x01(\v2\x0e.MetricRequestR\x06metric\"Z\n" +
	"\x13UpdateConfigRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12&\n" +
	"\x06config\x18\x02 \x01(\v2\x0e.ConfigRequestR\x06config\",\n" +
	"\rDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\x9c\x01\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"T\n" +
	"\tAlertList\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.StatusResponseR\x06status\x12\x1e\n" +
	"\x06alerts\x18\x02 \x03(\v2\x06.AlertR\x06alerts\">\n" +
	"\x13PostMetricsResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.StatusResponseR\x06status\"?\n" +
	"\x14UpdateConfigResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.StatusResponseR\x06status\"\\\n" +
	"\x11GetAlertsResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.StatusResponseR\x06status\x12\x1e\n" +
	"\x06alerts\x18\x02 \x03(\v2\x06.AlertR\x06alerts\"D\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\x12PostLimiterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_rate\x18\x02 \x01(\x01R\n" +
	"deviceRate\x12!\n" +
	"\fdevice_burst\x18\x03 \x01(\x05R\vdeviceBurst\">\n" +
	"\x13PostLimiterResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.StatusResponseR\x06status2\xee\x01\n" +
	"\n" +
	"IOTService\x128\n" +
	"\vPostMetrics\x12\x13.PostMetricsRequest\x1a\x14.PostMetricsResponse\x12;\n" +
	"\fUpdateConfig\x12\x14.UpdateConfigRequest\x1a\x15.UpdateConfigResponse\x12/\n" +
	"\tGetAlerts\x12\x0e.DeviceRequest\x1a\x12.GetAlertsResponse\x128\n" +
	"\vPostLimiter\x12\x13.PostLimiterRequest\x1a\x14.PostLimiterResponseB\x15Z\x13/iot_metric_serviceb\x06proto3"

var (
	file_pkg_grpc_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_service_proto_rawDescData []byte
)

func file_pkg_grpc_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_service_proto_rawDesc), len(file_pkg_grpc_service_proto_rawDesc)))
	})
	return file_pkg_grpc_service_proto_rawDescData
}

var file_pkg_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_grpc_service_proto_goTypes = []any{
	(*MetricRequest)(nil),         // 0: MetricRequest
	(*ConfigRequest)(nil),         // 1: ConfigRequest
	(*PostMetricsRequest)(nil),    // 2: PostMetricsRequest
	(*UpdateConfigRequest)(nil),   // 3: UpdateConfigRequest
	(*DeviceRequest)(nil),         // 4: DeviceRequest
	(*Alert)(nil),                 // 5: Alert
	(*AlertList)(nil),             // 6: AlertList
	(*PostMetricsResponse)(nil),   // 7: PostMetricsResponse
	(*UpdateConfigResponse)(nil),  // 8: UpdateConfigResponse
	(*GetAlertsResponse)(nil),     // 9: GetAlertsResponse
	(*StatusResponse)(nil),        // 10: StatusResponse
	(*PostLimiterRequest)(nil),    // 11: PostLimiterRequest
	(*PostLimiterResponse)(nil),   // 12: PostLimiterResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_pkg_grpc_service_proto_depIdxs = []int32{
	13, // 0: MetricRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: PostMetricsRequest.metric:type_name -> MetricRequest
	1,  // 2: UpdateConfigRequest.config:type_name -> ConfigRequest
	13, // 3: Alert.timestamp:type_name -> google.protobuf.Timestamp
	10, // 4: AlertList.status:type_name -> StatusResponse
	5,  // 5: AlertList.alerts:type_name -> Alert
	10, // 6: PostMetricsResponse.status:type_name -> StatusResponse
	10, // 7: UpdateConfigResponse.status:type_name -> StatusResponse
	10, // 8: GetAlertsResponse.status:type_name -> StatusResponse
	5,  // 9: GetAlertsResponse.alerts:type_name -> Alert
	10, // 10: PostLimiterResponse.status:type_name -> StatusResponse
	2,  // 11: IOTService.PostMetrics:input_type -> PostMetricsRequest
	3,  // 12: IOTService.UpdateConfig:input_type -> UpdateConfigRequest
	4,  // 13: IOTService.GetAlerts:input_type -> DeviceRequest
	11, // 14: IOTService.PostLimiter:input_type -> PostLimiterRequest
	7,  // 15: IOTService.PostMetrics:output_type -> PostMetricsResponse
	8,  // 16: IOTService.UpdateConfig:output_type -> UpdateConfigResponse
	9,  // 17: IOTService.GetAlerts:output_type -> GetAlertsResponse
	12, // 18: IOTService.PostLimiter:output_type -> PostLimiterResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_grpc_service_proto_init() }
func file_pkg_grpc_service_proto_init() {
	if File_pkg_grpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_service_proto_rawDesc), len(file_pkg_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_service_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_service_proto = out.File
	file_pkg_grpc_service_proto_goTypes = nil
	file_pkg_grpc_service_proto_depIdxs = nil
}
