FROM mcr.microsoft.com/vscode/devcontainers/go:1-1.24-bullseye

# Install Node.js
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends nodejs npm

